### PR TITLE
Efi modules

### PR DESCRIPTION
**Pull request by Florin65**
The efibootmgr is a WIP version (have to be reworked to avoid the git dependency).

### CODE REVIEW

**Comment by Florin65** [comment]
retest this please

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request closed without merging**
