### PR TITLE
linux-firmware: Bump to 20190615.

### PR DESCRIPTION
**Pull request by stumbles**
bump to 20190615

### CODE REVIEW

**Comment by stumbles** [comment]
Of course its on doppio you nimrod. I did an lget from my machine, so figure it out.

retest

**Comment by stumbles** [comment]
retest

**Comment by stumbles** [comment]
retest

**Comment by stumbles** [comment]
restest

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
