### PR TITLE
linux: version bumped to 4.2.

### PR DESCRIPTION
**Pull request by Florin65**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by Ratler** [comment]
Holding this merge until we've fixed openafs-driver, zfs and NVIDIA modules, they currently don't build with 4.2.

**Comment by Ratler** [comment]
zfs and openafs-driver fixed.

NVIDIA can't be fixed yet due to an interface regression in the kernel source causing GPL-incompatible build failure. Patch exist for 4.3 branch, hopefully it will be fixed in the 4.2 as well.
See https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=1dadafa86a779884f14a6e7a3ddde1a57b0a0a65

To work around this I'll add some regression patches for this kernel.

**Comment by Florin65** [comment]
cool

**Pull request merged**
