### PR TITLE
iptables: version bumped to 1.6.0.

### PR DESCRIPTION
**Pull request by Florin65**
For evaluation and testing.

### CODE REVIEW

**Comment by Florin65** [comment]
retest this please

**Comment by Florin65** [comment]
retest this please

**Comment by Ratler** [comment]
retest this please

**Comment by Ratler** [comment]
retest this please

**Comment by Ratler** [comment]
retest this please, sorry for the spam :)

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
