### PR TITLE
grub2: version bumped to 2.02.

### PR DESCRIPTION
**Pull request by Florin65**

### CODE REVIEW

**Comment by Florin65** [comment]
For testing purposes only. Usual precautions have to be taken (it might broke the boot).

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by Florin65** [comment]
Added new hacks borrowed from Arch Linux and adapted to Lunar. Added the efi support too (optional).
More testing is needed.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request closed without merging**
