### PR TITLE
gmp: Minor tweak to BUILD.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by dagbrown** [comment]
But why did you make this change?

**Comment by stumbles** [comment]
For example, if you run ldd -u -r /usr/lib/libgpgme.so, the results are;

Unused direct dependencies:
        /usr/lib/libgpg-error.so.0
        /usr/lib/libassuan.so.0
        /usr/lib/libm.so.6

So why link to libs not needed?

**Comment by stumbles** [comment]
Oh, for gmp ldd -u -r /usr/lib/libgmpxx.so;

Unused direct dependencies:
        /usr/lib/libm.so.6

**Comment by stumbles** [comment]
The lunar linker optimization Reduce (-Wl, --as-needed) doesn't work in this case.

**Comment by dagbrown** [comment]
Merging this but this optimization should possibly be global (in the gcc or ld plugin), not just for this one module.

**Pull request merged**
