### PR TITLE
gcc: Changing the fortran default to on, that is all.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by dagbrown** [comment]
But why?

**Comment by stumbles** [comment]
There are modules that need it like lapack and others and its easier and less hassle than finding, building, testing a standalone fortran. So why not use a compiler we alreaday have that can do the job.

**Comment by dagbrown** [comment]
I built an ISO with this PR applied, but the gcc in the resulting installation didn't include the FORTRAN compiler. If that was what you were hoping for, then it seems that this PR needs a little bit more work.

**Comment by stumbles** [comment]
Well I don't know what to tell ya. On any fresh install one of the first things I always to is enable it and it always installed /usr/bin/gfortran and its libraries.

**Comment by esselfe** [comment]
I think it's because the dialog choices are not taken by default from CONFIGURE, but from BUILD. The comment in CONFIGURE says "only lin -r gcc will trigger the language selector!" and in BUILD fortran should be added to "LANGUAGES="${LANGUAGES:=c++}"" I think.

**Comment by stumbles** [comment]
Testing a change. Basically changing to be LANGUAGES="${LANGUAGES:=c++,fortran} in CONFIGURE and BUILD, and removing the fortran option in CONFIGURE.

**Comment by stumbles** [comment]
Hmm. that's odd. Making LANGUAGES="${LANGUAGES:=c++,fortran} in both areas should have worked. What am I missing?

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by stumbles** [comment]
That worked.

**Pull request merged**
