### PR TITLE
shadow: version bumped to 4.14.2

### PR DESCRIPTION
**Pull request by esselfe**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by dagbrown** [comment]
This one fails in an iso build with:

    configure: error: readpassphrase() is missing, either from libc or libbsd

I guess something else needs to be bumped first?

**Comment by stumbles** [comment]
AFAICT it needs libbsd which depends on libmd both of which are in other.

**Comment by esselfe** [comment]
Closing with https://github.com/lunar-linux/moonbase-core/pull/3574

**Pull request closed without merging**
