### PR TITLE
gcc: Version bumped to 14.1.0

### PR DESCRIPTION
**Pull request by dagbrown**
We've done glibc and the kernel, now let's try the latest gcc!

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by dagbrown** [comment]
This breaks installwatch lol

So until installwatch is fixed I'm afraid I'll have to label this "iso_broken".

**Comment by Ratler** [comment]
@dagbrown there is a 14.2.0 available already fixing some regression issues in 14.1

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
