### PR TITLE
usbutils: Bump to 016.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
Retest this please.

**Comment by stumbles** [comment]
stderr: fatal: unable to access 'https://github.com/lunar-linux/moonbase-core.git/': OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443

**Comment by stumbles** [comment]
Retest this please.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
