### PR TITLE
linux-firmware:bump to 20240312

### PR DESCRIPTION
**Pull request by lhw828**

### CODE REVIEW

**Comment by dagbrown** [comment]
Your sha256sum is wrong, you should fix that.

**Comment by lhw828** [comment]
The reason is not related to the use of a non-official linux-firmware package in Lunar, and I am unable to adhere to the instructions for uploading the recompiled linux-firmware to the server of the lunar-liunx.

**Comment by lhw828** [comment]
The reason is not related to the use of a non-official linux-firmware package in Lunar, and I am unable to adhere to the instructions for uploading the recompiled linux-firmware to the server of the lunar-liunx.--2024-03-13 05:47:08--  http://download.lunar-linux.org/lunar/mirrors/linux-firmware-20240312.tar.xz
Resolving download.lunar-linux.org (download.lunar-linux.org)... 188.226.242.178, 2a03:b0c0:0:1010::5d:b001
Connecting to download.lunar-linux.org (download.lunar-linux.org)|188.226.242.178|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-03-13 05:47:08 ERROR 404: Not Found.

**Comment by dagbrown** [comment]
Try it again now.

**Comment by lhw828** [comment]
Building linux-firmware version 20240312
The kernel option CONFIG_FW_LOADER_COMPRESS is not enabled.
Please reconfigure and rebuild your kernel. Then try installing linux-firmware again.

**Comment by dagbrown** [comment]
Yo @Ratler, I found a bug in your CI. Or at least in lunar-docker. There's a chicken-and-egg problem because it doesn't include a default kernel config file, so anything trying to check for existing config is going to fall over.

This happens for sure in linux-firmware and systemd (in core, I don't know about elsewhere).

**Comment by dagbrown** [comment]
@lhw828 The patch in patch.d is no longer needed. Delete it and we should have a clean build.

**Comment by lhw828** [comment]
> @lhw828 The patch in patch.d is no longer needed. Delete it and we should have a clean build.

Building linux-firmware version 20240312
The kernel option CONFIG_FW_LOADER_COMPRESS is not enabled.
Please reconfigure and rebuild your kernel. Then try installing linux-firmware again.
Build step 'Execute managed script' marked build as failure
Discard old builds...

**Comment by dagbrown** [comment]
I've merged this into #3511 which I have confirmed builds fine and does not break the daily ISO.

**Pull request closed without merging**
