### PR TITLE
eudev: replace udev with eudev

### PR DESCRIPTION
**Pull request by Florin65**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by Florin65** [comment]
It conflicts with systemd so the CONFLICTS file have to be added at commit (with it it does not compile with jenkins).
udev module is broken for core anyway (it depends on lunar-init which is in others repo).

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request closed without merging**
