### PR TITLE
cmake: Bump to 3.31.0.

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by dagbrown** [comment]
This seems to have a dependency on libunistring, but that dependency comes from somewhere else so adding it to DEPENDS here might not be optimal. I’ll just flag this as iso_broken to keep it out of future ISOs until I figure out where that should actually go.

**Comment by stumbles** [comment]
libunistring is in core. 

But I don't see any anything about it in the compile log

**Comment by stumbles** [comment]
cmake does have this build switch we don't use; --no-system-libs.

**Comment by dagbrown** [comment]
Okay this one works fine WITHOUT the cmake bump (it successfully builds an iso), so it seems like the problem is with cmake, not libunistring.

**Comment by stumbles** [comment]
That's odd, libunistring uses autotools stuff.

Locally, 1.3 and 3.31.0 compiles fine regardless which I compile first. Though I've not tried making an ISO.

**Comment by stumbles** [comment]
Closing with PR; https://github.com/lunar-linux/moonbase-core/pull/3688

**Pull request closed without merging**
