### PR TITLE
systemd: version bumped to 230

### PR DESCRIPTION
**Pull request by Ratler**
- New upstream patches added

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by Florin65** [comment]
The docbook-xml optional depend line can be removed. docbook-xsl is depending on docbook-xml.

**Comment by Florin65** [comment]
Sorry, docbook-xsl have to be removed (no docbook-xml means no dosbook-xsl too).

**Comment by Florin65** [comment]
... and we can add to the PRE_BUILD file the following:

patch_it $SOURCE2 1 &&

if in_depends docbook-xml; then
  if [[ ! module_installed docbook-xsl ]]; then
    lin docbook-xsl
  fi
fi &&

./autogen.sh

to be sure both are installed if manpages build is requested.

**Comment by Florin65** [comment]
if [[ in_depends $MODULE docbook-xml ]]; then
  if [[ ! module_installed docbook-xsl ]]; then
    lin docbook-xsl
  fi
fi &&

i forgot the syntax for in_depends :(

**Comment by Ratler** [comment]
@Florin65 removing docbook-xml is enough. We should not be running lin from PRE_BUILD to satisfy a dependency. If someone have intentionally broken their dependency chain they are on their own. I'll have docbook-xml removed.

**Pull request merged**
