### PR TITLE
dbus: it optionally depends on libxslt, no docbook-xsl.

### PR DESCRIPTION
**Pull request by Florin65**

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by Florin65** [comment]
This module allows to clean up a bit the core. We can now move to others the modules:
libxsl libxml2 docbook-{sgml,xml,xsl} sgml-common. all other modules (in core) which depend on those modules use them as optional depends. For testing purpose!

**Comment by Florin65** [comment]
OK, i have tested this proposal on a VirtualBox install of core repo. I have removed the enumerated modules and relined dbus and gettext (without the optional libxml2 depend). All worked just fine.

**Comment by Florin65** [comment]
glib-2 optionally depends on libxslt, docbook-xml and docbook-xsl. it must to be rebuilded too.

**Pull request merged**
