### PR TITLE
expat: version bumped to 2.6.4

### PR DESCRIPTION
**Pull request by esselfe**

### CODE REVIEW

**Comment by esselfe** [comment]
lin/lget -w finally working with this :P

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by esselfe** [comment]
How does it break?

**Comment by dagbrown** [comment]
I wanted to temporarily exclude it from a future build to make sure it wasn't contributing to breaking the iso build along with libunistring and cmake. All looks good now though.

**Pull request merged**
