### PR TITLE
systemd: version bump to 221 + various fixes

### PR DESCRIPTION
**Pull request by Ratler**
- Added support for UEFI bootloader
- Tweaked depdencies list and added preferred defaults
- Added compat .pc files patch
- Added a couple of upstream fixes
- Tweaked which interface names that trigger the OLD naming scheme

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by Ratler** [comment]
Be aware that libgudev is no longer part of systemd. It will be provided in a standalone module when we merge this PR.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by Ratler** [comment]
New pr incoming in a bit to clean up the history.

**Pull request closed without merging**
