### PR TITLE
glibc: bump to 2.39

### PR DESCRIPTION
**Pull request by dagbrown**
Note that this PR should be merged at the same time as #3548 on account of how "crypt()" from glibc is disappearing and moving to an entirely different module.

### CODE REVIEW

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by esselfe** [comment]
So I've tested this out with the "future" iso from @dagbrown, so far everything I use normally in the graphical environment is working nicely.

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Comment by lunar-linux-b01** [comment]
SUCCESS!

**Pull request merged**
